name: Deploy to Hostinger

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, dom, zip, pdo, pdo_mysql, gd, exif, pcntl, bcmath, soap
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
        env:
          COMPOSER_PROCESS_TIMEOUT: 0
          COMPOSER_NO_INTERACTION: 1
          COMPOSER_NO_AUDIT: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install NPM dependencies
        run: npm install

      - name: Build assets
        run: |
          export NODE_OPTIONS=--no-experimental-fetch
          npm run build
        env:
          CI: false

      - name: Generate .env file
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env

      - name: Generate application key
        run: php artisan key:generate --force

      - name: Optimize Laravel
        run: |
          php artisan optimize
          php artisan view:cache
          php artisan route:cache
          php artisan config:cache

      - name: Deploy to Hostinger via SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: 65002
          SOURCE: ./
          TARGET: /home/u637719845/domains/groop.kindr.fr/public_html/
          EXCLUDE: "**/.git*,**/.git*/**,**/node_modules/**,**/tests/**,**/storage/framework/cache/**,**/storage/logs/**,**/vendor/bin/**,**/.github/**,**/.env.example,**/.gitignore,**/README.md"

      - name: Setup SSH key for remote commands
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Post-deploy – Laravel setup
        run: |
          ssh -i ~/.ssh/id_rsa -p 65002 -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            export PATH="$HOME/bin:$PATH"
            cd /home/u637719845/domains/groop.kindr.fr/public_html

            # Créer les dossiers nécessaires et fixer les permissions
            mkdir -p storage/logs storage/framework/{cache,sessions,views} bootstrap/cache
            chmod -R 775 storage bootstrap/cache

            # Installer les dépendances PHP avec Composer 2 local
            composer install --no-dev --optimize-autoloader

            # Exécuter les commandes Laravel
            php artisan migrate --force
            php artisan db:seed --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF
